Watching for file changes with StatReloader
Not Found: /
[27/Mar/2020 21:47:14] "GET / HTTP/1.1" 404 2134
Not Found: /favicon.ico
[27/Mar/2020 21:47:17] "GET /blog/ HTTP/1.1" 200 2175
[29/Mar/2020 09:42:23] "GET /blog/ HTTP/1.1" 200 2175
[29/Mar/2020 09:42:23] "GET /static/js/jquery-3.4.1.js HTTP/1.1" 304 0
[29/Mar/2020 09:42:23] "GET /static/js/bootstrap.js HTTP/1.1" 304 0
[29/Mar/2020 09:42:23] "GET /static/css/bootstrap.css HTTP/1.1" 200 197170
[29/Mar/2020 09:42:23] "GET /static/img/tsingtao.jpg HTTP/1.1" 304 0
Not Found: /favicon.ico
[29/Mar/2020 09:52:56] "GET /blog/ HTTP/1.1" 200 2175
[29/Mar/2020 09:52:56] "GET /static/css/bootstrap.css HTTP/1.1" 200 197170
Not Found: /favicon.ico
/home/zzx/projects/mysite/account/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 27, 2020 - 21:47:02
Django version 3.0.3, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/home/zzx/projects/mysite/account/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 29, 2020 - 09:55:31
Django version 3.0.3, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/home/zzx/projects/mysite/account/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 29, 2020 - 09:55:49
Django version 3.0.3, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/home/zzx/projects/mysite/account/forms.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 29, 2020 - 09:58:08
Django version 3.0.3, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/home/zzx/projects/mysite/account/forms.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 29, 2020 - 10:05:26
Django version 3.0.3, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[29/Mar/2020 10:13:51] "GET /blog/ HTTP/1.1" 200 2175
[29/Mar/2020 10:13:51] "GET /static/css/bootstrap.css HTTP/1.1" 200 197170
Not Found: /favicon.ico
/home/zzx/projects/mysite/account/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 29, 2020 - 10:10:03
Django version 3.0.3, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/core/management/base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/zzx/projects/mysite/mysite/urls.py", line 22, in <module>
    path('account/',include(('account.urls','account'),namespace='account')),
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/zzx/projects/mysite/account/urls.py", line 2, in <module>
    from . import views
  File "/home/zzx/projects/mysite/account/views.py", line 47, in <module>
    @login_required(login_url='/account/login')
NameError: name 'login_required' is not defined

/home/zzx/projects/mysite/account/views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/core/management/base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/zzx/projects/mysite/mysite/urls.py", line 22, in <module>
    path('account/',include(('account.urls','account'),namespace='account')),
  File "/home/zzx/projects/mysite-venv/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/zzx/projects/mysite/account/urls.py", line 2, in <module>
    from . import views
  File "/home/zzx/projects/mysite/account/views.py", line 46, in <module>
    @login_required(login_url='/account/login')
NameError: name 'login_required' is not defined

Performing system checks...

Watching for file changes with StatReloader
